### ISSUE TITLE
Hunter runs to target

### ISSUE THREAD

**Issue by zeest** [playerbot/mangos#2]
Instead of staying back and attacking ranged, the hunter playerbot shoots once, then runs in and melees.

**Comment by blueboy** [comment]
Thanks for the feedback. I created a fix for this sometime back on the TBC playerbot backport, but never got around to including it in the portal code. I will remedy this shortly, with a few other enhancements.

The issue was further aggravated by the hunter bots not finding appropriate ammo. For example, my hunter (level 19) had an abundance of 'Sharp Arrows' (req level 10), but the ammo check was insisting on 'Rough Arrows' (no level req). As such, the hunter was being forced to melee each time. I have now added a function to check and set appropriate ammo (if possible) during the first combat maneuver. It appears to work fine, but I would appreciate it if you could double check. I assume you are setting the hunter up as a 'ranged dps' to assist the healer who usually holds back from melee combat. (If the priest's name is three and the hunter bot's name is two) Use the following command to set combat orders

```
/w two orders combat assist three
```

@EDIT fix committed: https://github.com/blueboy/portal/commit/0894c3c4dc15cd3dbedba9f0ca5551ea28eb9859

Please note that this fix will be first tested in our portal beta code before it is merged with our playerbot release code.

Hope this helps
